config/routes.rb
Phoenii::Application.routes.draw do
  resources :users

  get "sessions/new"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "invest" => "investors#new", :as => "invest"
  get "start" => "businesses#new", :as => "start"

  resources :sessions

  resources :businesses do
    resource :page
    resources :investments
    resources :reports
  end

  resources :users do
    resource :business do
      resource :page
      resources :investments
    end
    resources :investments
    resources :reports
  end

  root :to => 'front#show'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json
  def index
    if current_user.business
      redirect_to root_url
      return
    end
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @user = current_user
    if @user.business
      @business = @user.business
    else
      @business = Business.find params[:id]
    end
    @business.update_invested

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new
    @business.build_page

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])
    @business.user_id = current_user.id if current_user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>

  <%= render :partial => 'layouts/form_errors', :locals => {:object => @business} %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Goal Investment (in dollars)" %><br />
    <%= f.text_field :goal_investment %>
  </div>
  <div class="field">
    <%= f.label "Total Equity Offered (as a percentage)" %><br />
    <%= f.text_field :equity_offered %>
  </div>
  <div class="field">
    <%= f.label "Paragraph Pitch" %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label "Your Business' Image" %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h2>Editing Your Business</h2>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<% @businesses.each do |business| %>
  <div class="card_small">
    <h2><%= link_to business.name, business %></h2>

    <div id="photodiv">
  <% if business.photo.exists? %> <%= image_tag business.photo.url(:thumb) %>
  <% else %> <% end %>
    </div>

    <div id="data">
    <p class="card_data" id="desc"><%= business.desc %></p>
    <% inv = current_user.investments.find {|i| i.business == business} %>
    <% if inv %>
      <p class="card_data" id="view_investment"><%= link_to "View Your Investment", business_investment_path(business,inv) %></p>
    <% else %>
      <p class="card_data" id="invest"><%= link_to 'Invest', new_business_investment_path(business) %></p>
    <% end %>
    <script>placeStatusBar(<%= business.goal_investment / business.invested_amount  %>)</script><br />
    </div>
  </div>
<% end %>
</table>

<br />

app/views/businesses/new.html.erb
<h2>Start a Business</h2>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<div class="card">
  <h2><%= @business.name %></h2>
  <div id="photodiv">
  <% if @business.photo.exists? %> <%= image_tag @business.photo.url(:medium) %>
  <% else %> <% end %>
  </div>
  <div class="data">
    <p class="card_data" id="blurb"><%= @business.desc %></p>
    <script>placeStatusBar(<%= @business.goal_investment / @business.invested_amount  %>)</script><br />
    <p class="card_data" id="investments">
      <b>Goal:</b> <%= number_to_currency(@business.goal_investment) %> <br />
      <b>Invested:</b> <%= number_to_currency(@business.invested_amount) %>
    </p>
    <p class="card_data" id="equity">
    <b>Equity offered:</b> <%= @business.equity_offered %>% <br />
    <b>Given:</b> <%= @business.equity_given %>%
    </p>
    <% inv = current_user.investments.find {|i| i.business == @business} %>
    <% if inv %>
      <p class="card_data" id="view_investment">You invested! <%= link_to "View Your Investment", business_investment_path(@business,inv) %></p>
    <% elsif !inv && !current_user.business %>
      <p id="invest"><%= link_to 'Invest', new_business_investment_path(@business) %></p>
    <% end %>
    <% if current_user.business %>
      <p><%= link_to 'Edit', edit_business_path(@business) %></p>
    <% end %>
  </div>

<ul>