config/routes.rb
Phoenii::Application.routes.draw do
  resources :users

  get "sessions/new"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "invest" => "investors#new", :as => "invest"
  get "start" => "businesses#new", :as => "start"

  resources :sessions

  resources :businesses do
    resource :page
    resources :investments
    resources :reports
  end

  resources :users do
    resource :business do
      resource :page
      resources :investments
    end
    resources :investments
    resources :reports
  end

  root :to => 'front#show'

end

app/models/investment.rb
class Investment < ActiveRecord::Base

  belongs_to :user
  belongs_to :business

  after_create :update_business

  validates :business_id,
            :presence => true,
            :numericality => true
  validates :user_id,
            :presence => true,
            :numericality => true
  validates :amount,
            :presence => true,
            :numericality => true

  def equity
    denom = self.business.goal_investment
    if self.business.invested_amount >= denom
      return 0
    elsif denom && denom > 0
      offered = self.business.equity_offered / 100.0
      self.amount.to_f / self.business.goal_investment.to_f * 100 * offered
    else
      return 0
    end
  end

  private
  
  def update_business
    if self.business.invested_amount
      self.business.invested_amount += self.amount
    else
      self.business.invested_amount = self.amount
    end
    self.business.save
  end

end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  # GET /investments
  # GET /investments.json
  def index
    @user = current_user
    if current_user.business
      @investments = current_user.business.investments
    else
      @investments = @user.investments
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @investments }
    end
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
    # XXX not scoped
    @investment = Investment.find params[:id]
    @business = @investment.business
    @user = @investment.user
   #if params[:user_id]
   #  @user = User.find params[:user_id]
   #  @business = @investment.business
   #elsif params[:business_id]
   #  @business = User.find params[:user_id]
   #  @user = @investment.user
   #end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/new
  # GET /investments/new.json
  def new
    @business = Business.find params[:business_id]
    @user = current_user
    @investment = @user.investments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @investment }
    end
  end

  # GET /investments/1/edit
  def edit
    @investment = Investment.find(params[:id])
  end

  # POST /investments
  # POST /investments.json
  def create
    @user = current_user
    @business = Business.find params[:investment][:business_id]
    @investment = @user.investments.build params[:investment]

    respond_to do |format|
      if @investment.save
        format.html { redirect_to user_investment_url(@user, @investment), notice: 'Investment was successfully created.' }
        format.json { render json: @investment, status: :created, location: @investment }
      else
        format.html { render action: "new" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /investments/1
  # PUT /investments/1.json
  def update
    @investment = Investment.find(params[:id])

    respond_to do |format|
      if @investment.update_attributes(params[:investment])
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment = Investment.find(params[:id])
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_for [@user, @investment] do |f| %>
  <%= render :partial => 'layouts/form_errors', :locals => {:object => @investment} %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %><br />
    <%= f.hidden_field :business_id, :value => @business.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<h2>Investments</h2>

<table>
  <tr>
    <% if current_user.business %>
      <th class="startTable">Investor</th>
    <% else  %>
      <th class="startTable">Business</th>
    <% end %>
    <th>Amount</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @investments.each do |investment| %>
  <tr>
    <% if current_user.business %>
      <td class="startTable"><%= link_to investment.user.name, investment.user %></td>
    <% else %>
      <td class="startTable"><%= link_to investment.business.name, business_path(investment.business) %></td>
    <% end %>
    <td><%= number_to_currency investment.amount %></td>
    <td><%= investment.created_at.strftime('%b %e, %Y') %></td>
    <td><%= link_to "Show", user_investment_path(current_user, investment) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/investments/new.html.erb
<h2>Make an Investment Towards <%= @business.name %></h2>

<p>
<b>Goal:</b> <%= number_to_currency @business.goal_investment %></b><br />
<b>Equity offered:</b> <%= @business.equity_offered %>%</b><br />
<b>Equity given:</b> <%= @business.equity_given %>%</b><br />
<b>Dollars per percentage of equity:</b> <%= number_to_currency @business.goal_investment / @business.equity_offered %>

</p>

<%= render 'form' %>

<%= link_to 'Back', user_investments_path(current_user) %>

app/views/investments/show.html.erb
<h2>Investment Details</h2>

<div id="investment_info">
  <p id="show_investor">
    <b>Investor:</b>
    <%= @user.name %>
  </p>

  <p id="show_business">
    <b>Business:</b>
    <%= link_to @investment.business.name, business_path(@investment.business) %>
  </p>

  <p id="show_amount">
    <b>Amount:</b>
    <%= number_to_currency @investment.amount %>
  </p>

  <p id="show_equity">
    <b>Percentage Equity:</b>
    <%= @investment.equity %>%
  </p>

  <p id="show_created">
    <b>Created:</b>
    <%= @investment.created_at.strftime('%b %e, %Y') %>
  </p>
</div>