config/routes.rb
Phoenii::Application.routes.draw do
  resources :users

  get "sessions/new"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "invest" => "investors#new", :as => "invest"
  get "start" => "businesses#new", :as => "start"

  resources :sessions

  resources :businesses do
    resource :page
    resources :investments
    resources :reports
  end

  resources :users do
    resource :business do
      resource :page
      resources :investments
    end
    resources :investments
    resources :reports
  end

  root :to => 'front#show'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :business
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @business = current_user.business
    @reports = @business.reports

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @business = current_user.business
    @report = @business.reports.find params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @business = current_user.business
    @report = @business.reports.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @business = current_user.business
    @report = @business.reports.build params[:report]

    respond_to do |format|
      if @report.save
        format.html { redirect_to [@business, @report], notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :ok }
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for [@business,@report] do |f| %>
  <%= render :partial => 'layouts/form_errors', :locals => {:object => @report} %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h2>Reports</h2>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.content %></td>
    <td><%= link_to 'Show', business_report_path(@business,report) %></td>
    <td><%= link_to 'Edit', edit_business_report_path(@business, report) %></td>
    <td><%= link_to 'Destroy', business_report_path(@business,report), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% if current_user.business %>
  <%= link_to 'Create a New Report', new_business_report_path(current_user.business) %>
<% end %>

app/views/reports/new.html.erb
<h2>Report Your Business Status</h2>

<%= render 'form' %>

<%= link_to 'Back', business_reports_path(@business) %>

app/views/reports/show.html.erb
<h2>Business Report for <%= current_user.business.name %></h2>

<p>
  <b>Business:</b>
  <%= @report.business_id %>
</p>

<p>
  <b>Content:</b>
  <%= @report.content %>
</p>


<%= link_to 'Edit', edit_business_report_path(@business,@report) %> |
<%= link_to 'Back', business_reports_path(@business) %>