config/routes.rb
Phoenii::Application.routes.draw do
  resources :users

  get "sessions/new"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "invest" => "investors#new", :as => "invest"
  get "start" => "businesses#new", :as => "start"

  resources :sessions

  resources :businesses do
    resource :page
    resources :investments
    resources :reports
  end

  resources :users do
    resource :business do
      resource :page
      resources :investments
    end
    resources :investments
    resources :reports
  end

  root :to => 'front#show'

end

app/views/layouts/_form_errors.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:</p>

      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phoenii | Business rises again.</title>
  <%= stylesheet_link_tag "progressbar" %>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag "style_inner" %>
  <%= stylesheet_link_tag "tablestyle" %>
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,700italic,400italic' rel='stylesheet' type='text/css' /> 
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery-ui" %>
  <%= javascript_include_tag "progressbar" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container"> 

	<div id="header">
    <h1><%= link_to "PHOENII", root_url %></h1>
  <% if current_user %>
    <h2>Logged in as <%= link_to current_user.name, current_user %></h2>
		
		<div id="logout">
      <%= link_to "Log out", logout_url %>
		</div>
	</div>
  <% end %>

  <!-- Nav -->
  <div id="nav">
    <% if current_user && current_user.role == "Investor" %>
      <h3 class="node" id="leftN"><%= link_to "Browse", businesses_path %></h3>
      <h3 class="node" id="middleN"><%= link_to "Reports", user_investments_path(current_user) %></h3>
      <h3 class="node" id="rightN"><%= link_to "Card", current_user %></h3>
    <% elsif current_user && current_user.role == "Entrepreneur" %>
      <% if current_user.business %>
        <h3 class="node" id="leftN"><%= link_to "Stats", business_investments_path(current_user.business) %></h3>
        <h3 class="node" id="middleN"><%= link_to "Page", business_page_path(current_user.business) %></h3>
      <% end %>
      <% if current_user.business %>
        <h3 class="node" id="rightN"><%= link_to "Card", user_business_path(current_user) %></h3>
      <% else %>
        <h3 class="node" id="rightN"><%= link_to "Start a Business", new_user_business_path(current_user) %></h3>
      <% end %>
    <% end %>
  </div>



<div id="content">
  <!-- Notices -->
  <% flash.each do |key, msg| %>
    <div class="notice">
      <p class="message"> <strong><%= msg %> </strong> </p>
    </div>
  <% end %>

  <%= yield %>
</div>

</div>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phoenii | Business rises again.</title>
  <%= stylesheet_link_tag    "style" %>
	<link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,700italic,400italic' rel='stylesheet' type='text/css' /> 
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "loginAnim" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container"> 

<div id="intro">
  <h1><%= link_to "PHOENII", root_url %></h1>
	<div id="call">
		<h2>Business rises and falls.</h2>
		<h3>Not of its own volition, but by the action of its agents.</h3>
	</div>
</div>

  <!-- Notices -->
  <% flash.each do |key, msg| %>
    <div class="notice">
      <p class="message"> <strong><%= msg %> </strong> </p>
    </div>
  <% end %>

<%= yield %>

</div>

</body>
</html>